[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [
    { access = "read", path = "./test/Mint150Wrapper.huff" }
]
optimizer = true
optimizer_runs = 1000000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config